// ─────────────────────────────────────────────────────────────────────────────
//  Test Case Agent — Exporters
//  Formats: Markdown | CSV | JSON | Playwright .spec.ts
// ─────────────────────────────────────────────────────────────────────────────

import { IssueAnalysis, JiraIssue, TestCase } from './types';

export function formatAsMarkdown(testCases: TestCase[], issue: JiraIssue, analysis: IssueAnalysis): string {
  const ts = new Date().toISOString();
  let md = `# Test Cases — ${issue.key}: ${issue.summary}\n\n`;
  md += `| Field | Value |\n|---|---|\n`;
  md += `| **Issue** | [${issue.key}](https://ibm-middleware.atlassian.net/browse/${issue.key}) |\n`;
  md += `| **Type** | ${issue.issueType} |\n| **Priority** | ${issue.priority} |\n| **Status** | ${issue.status} |\n`;
  if (issue.assignee) md += `| **Assignee** | ${issue.assignee} |\n`;
  if (issue.epicKey) md += `| **Epic** | ${issue.epicKey} |\n`;
  if (issue.sprint) md += `| **Sprint** | ${issue.sprint} |\n`;
  if (issue.components.length) md += `| **Components** | ${issue.components.join(', ')} |\n`;
  if (issue.labels.length) md += `| **Labels** | ${issue.labels.join(', ')} |\n`;
  md += `| **Generated** | ${ts} |\n\n`;
  if (issue.acceptanceCriteria) md += `## Acceptance Criteria\n\n${issue.acceptanceCriteria}\n\n`;
  const byType: Record<string, number> = {};
  const byCat: Record<string, number> = {};
  for (const t of testCases) { byType[t.type] = (byType[t.type] ?? 0) + 1; byCat[t.category ?? 'General'] = (byCat[t.category ?? 'General'] ?? 0) + 1; }
  md += `## Summary\n\n**Total:** ${testCases.length} | **Complexity:** ${analysis.complexity} | **Types:** ${analysis.suggestedTypes.join(', ')}\n\n`;
  md += `### By Type\n` + Object.entries(byType).map(([t, n]) => `- ${t}: ${n}`).join('\n') + '\n\n';
  md += `### By Category\n` + Object.entries(byCat).map(([c, n]) => `- ${c}: ${n}`).join('\n') + '\n\n---\n\n';
  const grouped = new Map<string, TestCase[]>();
  for (const t of testCases) { const c = t.category ?? 'General'; if (!grouped.has(c)) grouped.set(c, []); grouped.get(c)!.push(t); }
  for (const [cat, cases] of grouped) {
    md += `## ${cat}\n\n`;
    for (const t of cases) {
      md += `### ${t.id}: ${t.title}\n\n**Priority:** ${t.priority} | **Type:** ${t.type} | **Automatable:** ${t.automatable ? '✅' : '❌'}\n\n`;
      md += `#### Preconditions\n` + t.preconditions.map((p) => `- ${p}`).join('\n') + '\n\n';
      md += `#### Test Steps\n\n| # | Action | Expected Result |\n|---|--------|-----------------|\n`;
      for (const s of t.testSteps) md += `| ${s.stepNumber} | ${s.action.replace(/\|/g, '\\|')} | ${s.expectedResult.replace(/\|/g, '\\|')} |\n`;
      md += `\n#### Expected Result\n${t.expectedResult}\n\n`;
      if (t.testData?.length) md += `#### Test Data\n` + t.testData.map((d) => `- ${d}`).join('\n') + '\n\n';
      if (t.notes) md += `> 💡 ${t.notes}\n\n`;
      md += `---\n\n`;
    }
  }
  md += `\n*Generated by JIRA Test Case AI Agent — ${ts}*\n`;
  return md;
}

export function formatAsCSV(testCases: TestCase[]): string {
  const esc = (s: string) => `"${String(s ?? '').replace(/"/g, '""')}"`;
  // Columns match the requested format:
  // Test Case ID, Title, Priority, Type, Preconditions, Test Steps, Expected Result, Test Data, Notes
  const header = ['Test Case ID','Title','Priority','Type','Preconditions','Test Steps','Expected Result','Test Data','Notes'].map(esc).join(',');
  const rows = testCases.map((t) => [
    t.id,
    t.title,
    t.priority,
    t.type,
    t.preconditions.join(' | '),
    t.testSteps.map((s) => `${s.stepNumber}. ${s.action} -> ${s.expectedResult}`).join(' | '),
    t.expectedResult,
    (t.testData ?? []).join(' | '),
    t.notes ?? '',
  ].map(esc).join(','));
  return [header, ...rows].join('\n');
}

export function formatAsJSON(testCases: TestCase[], issue: JiraIssue, analysis: IssueAnalysis): string {
  return JSON.stringify({ meta: { issueKey: issue.key, summary: issue.summary, issueType: issue.issueType, priority: issue.priority, status: issue.status, complexity: analysis.complexity, suggestedTypes: analysis.suggestedTypes, generatedAt: new Date().toISOString(), totalTestCases: testCases.length }, testCases }, null, 2);
}

export function formatAsPlaywright(testCases: TestCase[], issue: JiraIssue): string {
  const auto = testCases.filter((t) => t.automatable !== false);
  let s = `import { test, expect } from '@playwright/test';\n\n/**\n * AUTO-GENERATED for ${issue.key}: ${issue.summary}\n * Generated: ${new Date().toISOString()}\n */\n\n`;
  const grouped = new Map<string, TestCase[]>();
  for (const t of auto) { const c = t.category ?? 'General'; if (!grouped.has(c)) grouped.set(c, []); grouped.get(c)!.push(t); }
  for (const [cat, cases] of grouped) {
    s += `test.describe('${issue.key} — ${cat}', () => {\n\n`;
    for (const t of cases) {
      s += `  /** ${t.id}: ${t.title} | Priority: ${t.priority} | Type: ${t.type} */\n`;
      s += `  test('${t.id} — ${t.title.replace(/'/g, "\\'")}'\, async ({ page }) => {\n`;
      s += `    // Preconditions:\n` + t.preconditions.map((p) => `    //   - ${p}`).join('\n') + '\n\n';
      for (const step of t.testSteps) {
        s += `    // Step ${step.stepNumber}: ${step.action}\n`;
        if (step.stepNumber === 1 && /navigate|open|go to/i.test(step.action)) s += `    await page.goto('/* TODO: URL */')\;\n`;
        else if (/click|button|press/i.test(step.action)) s += `    await page.getByRole('button', { name: '/* TODO */' }).click()\;\n`;
        else if (/fill|type|enter|input/i.test(step.action)) s += `    await page.getByLabel('/* TODO */').fill('/* value */')\;\n`;
        else if (/verify|check|assert|visible|display/i.test(step.action)) s += `    await expect(page.locator('/* TODO */')).toBeVisible()\;\n`;
        else s += `    // TODO: implement — ${step.action}\n`;
        s += `    // Expected: ${step.expectedResult}\n\n`;
      }
      s += `  });\n\n`;
    }
    s += `});\n\n`;
  }
  s += `// Made with JIRA Test Case AI Agent\n`;
  return s;
}

// Made with Bob
