// ─────────────────────────────────────────────────────────────────────────────
//  Test Case Agent — Exporters
//  Formats: Markdown | CSV | JSON | Playwright .spec.ts | XLSX
// ─────────────────────────────────────────────────────────────────────────────

import * as XLSX from 'xlsx';
import { IssueAnalysis, JiraIssue, TestCase } from './types';

export function formatAsMarkdown(testCases: TestCase[], issue: JiraIssue, analysis: IssueAnalysis): string {
  const ts = new Date().toISOString();
  let md = `# Test Cases — ${issue.key}: ${issue.summary}\n\n`;
  md += `| Field | Value |\n|---|---|\n`;
  md += `| **Issue** | [${issue.key}](https://ibm-middleware.atlassian.net/browse/${issue.key}) |\n`;
  md += `| **Type** | ${issue.issueType} |\n| **Priority** | ${issue.priority} |\n| **Status** | ${issue.status} |\n`;
  if (issue.assignee) md += `| **Assignee** | ${issue.assignee} |\n`;
  if (issue.epicKey) md += `| **Epic** | ${issue.epicKey} |\n`;
  if (issue.sprint) md += `| **Sprint** | ${issue.sprint} |\n`;
  if (issue.components.length) md += `| **Components** | ${issue.components.join(', ')} |\n`;
  if (issue.labels.length) md += `| **Labels** | ${issue.labels.join(', ')} |\n`;
  md += `| **Generated** | ${ts} |\n\n`;
  if (issue.acceptanceCriteria) md += `## Acceptance Criteria\n\n${issue.acceptanceCriteria}\n\n`;
  const byType: Record<string, number> = {};
  const byCat: Record<string, number> = {};
  for (const t of testCases) { byType[t.type] = (byType[t.type] ?? 0) + 1; byCat[t.category ?? 'General'] = (byCat[t.category ?? 'General'] ?? 0) + 1; }
  md += `## Summary\n\n**Total:** ${testCases.length} | **Complexity:** ${analysis.complexity} | **Types:** ${analysis.suggestedTypes.join(', ')}\n\n`;
  md += `### By Type\n` + Object.entries(byType).map(([t, n]) => `- ${t}: ${n}`).join('\n') + '\n\n';
  md += `### By Category\n` + Object.entries(byCat).map(([c, n]) => `- ${c}: ${n}`).join('\n') + '\n\n---\n\n';
  const grouped = new Map<string, TestCase[]>();
  for (const t of testCases) { const c = t.category ?? 'General'; if (!grouped.has(c)) grouped.set(c, []); grouped.get(c)!.push(t); }
  for (const [cat, cases] of grouped) {
    md += `## ${cat}\n\n`;
    for (const t of cases) {
      md += `### ${t.id}: ${t.title}\n\n**Priority:** ${t.priority} | **Type:** ${t.type} | **Automatable:** ${t.automatable ? '✅' : '❌'}\n\n`;
      md += `#### Preconditions\n` + t.preconditions.map((p) => `- ${p}`).join('\n') + '\n\n';
      md += `#### Test Steps\n\n| # | Action | Expected Result |\n|---|--------|-----------------|\n`;
      for (const s of t.testSteps) md += `| ${s.stepNumber} | ${s.action.replace(/\|/g, '\\|')} | ${s.expectedResult.replace(/\|/g, '\\|')} |\n`;
      md += `\n#### Expected Result\n${t.expectedResult}\n\n`;
      if (t.testData?.length) md += `#### Test Data\n` + t.testData.map((d) => `- ${d}`).join('\n') + '\n\n';
      if (t.notes) md += `> 💡 ${t.notes}\n\n`;
      md += `---\n\n`;
    }
  }
  md += `\n*Generated by JIRA Test Case AI Agent — ${ts}*\n`;
  return md;
}

export function formatAsCSV(testCases: TestCase[]): string {
  const esc = (s: string) => `"${String(s ?? '').replace(/"/g, '""')}"`;
  // Columns match the requested format:
  // Test Case ID, Title, Priority, Type, Preconditions, Test Steps, Expected Result, Test Data, Notes
  const header = ['Test Case ID','Title','Priority','Type','Preconditions','Test Steps','Expected Result','Test Data','Notes'].map(esc).join(',');
  const rows = testCases.map((t) => [
    t.id,
    t.title,
    t.priority,
    t.type,
    t.preconditions.join(' | '),
    t.testSteps.map((s) => `${s.stepNumber}. ${s.action} -> ${s.expectedResult}`).join(' | '),
    t.expectedResult,
    (t.testData ?? []).join(' | '),
    t.notes ?? '',
  ].map(esc).join(','));
  return [header, ...rows].join('\n');
}

export function formatAsJSON(testCases: TestCase[], issue: JiraIssue, analysis: IssueAnalysis): string {
  return JSON.stringify({ meta: { issueKey: issue.key, summary: issue.summary, issueType: issue.issueType, priority: issue.priority, status: issue.status, complexity: analysis.complexity, suggestedTypes: analysis.suggestedTypes, generatedAt: new Date().toISOString(), totalTestCases: testCases.length }, testCases }, null, 2);
}

/**
 * Write test cases to an XLSX workbook buffer.
 * Sheet 1 — "Test Cases": one row per test case, columns matching the CSV format.
 * Sheet 2 — "Summary": counts by type and category.
 */
export function formatAsXLSX(testCases: TestCase[], issue: JiraIssue, analysis: IssueAnalysis): Buffer {
  // ── Sheet 1: Test Cases ──────────────────────────────────────────────────
  const tcRows = testCases.map((t) => ({
    'Test Case ID':   t.id,
    'Title':          t.title,
    'Priority':       t.priority,
    'Type':           t.type,
    'Category':       t.category ?? '',
    'Preconditions':  t.preconditions.join(' | '),
    'Test Steps':     t.testSteps.map((s) => `${s.stepNumber}. ${s.action} -> ${s.expectedResult}`).join(' | '),
    'Expected Result': t.expectedResult,
    'Test Data':      (t.testData ?? []).join(' | '),
    'Notes':          t.notes ?? '',
    'Automatable':    t.automatable ? 'Yes' : 'No',
  }));

  const tcSheet = XLSX.utils.json_to_sheet(tcRows);

  // Column widths
  tcSheet['!cols'] = [
    { wch: 22 },  // Test Case ID
    { wch: 55 },  // Title
    { wch: 10 },  // Priority
    { wch: 14 },  // Type
    { wch: 22 },  // Category
    { wch: 50 },  // Preconditions
    { wch: 80 },  // Test Steps
    { wch: 55 },  // Expected Result
    { wch: 40 },  // Test Data
    { wch: 40 },  // Notes
    { wch: 12 },  // Automatable
  ];

  // ── Sheet 2: Summary ─────────────────────────────────────────────────────
  const byType: Record<string, number> = {};
  const byCat:  Record<string, number> = {};
  for (const t of testCases) {
    byType[t.type] = (byType[t.type] ?? 0) + 1;
    byCat[t.category ?? 'General'] = (byCat[t.category ?? 'General'] ?? 0) + 1;
  }

  const summaryRows = [
    { Field: 'Issue',       Value: issue.key },
    { Field: 'Summary',     Value: issue.summary },
    { Field: 'Type',        Value: issue.issueType },
    { Field: 'Priority',    Value: issue.priority },
    { Field: 'Status',      Value: issue.status },
    { Field: 'Complexity',  Value: analysis.complexity },
    { Field: 'Total TCs',   Value: String(testCases.length) },
    { Field: 'Generated',   Value: new Date().toISOString() },
    { Field: '', Value: '' },
    { Field: '--- By Type ---', Value: '' },
    ...Object.entries(byType).map(([k, v]) => ({ Field: k, Value: String(v) })),
    { Field: '', Value: '' },
    { Field: '--- By Category ---', Value: '' },
    ...Object.entries(byCat).map(([k, v]) => ({ Field: k, Value: String(v) })),
  ];

  const summarySheet = XLSX.utils.json_to_sheet(summaryRows);
  summarySheet['!cols'] = [{ wch: 26 }, { wch: 60 }];

  // ── Workbook ──────────────────────────────────────────────────────────────
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, tcSheet, 'Test Cases');
  XLSX.utils.book_append_sheet(wb, summarySheet, 'Summary');

  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }) as Buffer;
}

// Made with Bob
