// ─────────────────────────────────────────────────────────────────────────────
//  Test Case Agent — Generator
//
//  ARCHITECTURE (Bob-driven, prompt-as-source-of-truth):
//
//  The test cases are generated by Bob reasoning over the full JIRA + repo
//  context. All QA reasoning rules (categories, priorities, step quality,
//  preconditions, deduplication) live in prompts/test-case-generation.md.
//
//  This file handles:
//    - Writing the Bob instruction file (context + prompt → .md file)
//    - Parsing the CSV Bob produces back into TestCase[]
//    - Fallback minimal generator for standalone CLI use (no Bob)
//    - TestCaseAgentGenerator class used by workflow.ts and CLI
//
//  What is NOT here (intentionally):
//    - buildSteps() hardcoded step templates
//    - derivePreconditions() keyword matching
//    - buildScenarioGroups() pattern extraction
//    All of that now lives only in prompts/test-case-generation.md.
// ─────────────────────────────────────────────────────────────────────────────

import * as fs from 'fs';
import * as path from 'path';
import { analyseIssue } from './ai-analyzer';
import { buildContext, renderFullContextForBob, FullContext } from './context-builder';
import { formatAsCSV, formatAsMarkdown, formatAsXLSX } from './exporters';
import { fetchFromRestApi } from './jira-fetcher';
import { IssueAnalysis, JiraIssue, OutputFormat, TestCase, TestPriority, TestStep, TestType } from './types';

const pad = (n: number) => String(n).padStart(3, '0');

// ─── Bob instruction file writer ──────────────────────────────────────────────
//
// Writes a self-contained Markdown file that Bob reads and acts on.
// The file contains:
//   1. The generation rules from prompts/test-case-generation.md
//   2. The full JIRA + repo context rendered by renderFullContextForBob()
//   3. An explicit instruction to save the CSV to the specified output path
//
// Bob reads this file, reasons over it, and writes the CSV.
// The workflow then calls parseCsvToTestCases() to load it back into memory.

export function writeBobInstructionFile(
  ctx: FullContext,
  csvOutputPath: string,
  instructionDir: string,
): string {
  const instructionPath = path.join(instructionDir, `${ctx.issueKey}-bob-instructions.md`);
  const generationRules = ctx.generationPrompt || '(prompts/test-case-generation.md not found — apply QA best practices)';

  const content = [
    `# Bob Test Case Generation Instructions — ${ctx.issueKey}`,
    '',
    '## Your Role',
    '',
    'You are a Senior QA Architect. Read the generation rules below and then',
    'reason over the JIRA issue context to produce comprehensive test cases.',
    '',
    '---',
    '',
    '## Generation Rules',
    '',
    generationRules,
    '',
    '---',
    '',
    '## Issue to Process',
    '',
    renderFullContextForBob(ctx),
    '',
    '---',
    '',
    '## Output Instruction',
    '',
    `Generate all applicable test cases and save the CSV to:`,
    `  **${csvOutputPath}**`,
    '',
    'CSV columns (exact):',
    '```',
    'Test Case ID, Title, Priority, Type, Preconditions, Test Steps, Expected Result, Test Data, Notes',
    '```',
    '',
    '- `Preconditions`: pipe-separated list, specific to THIS scenario (not generic boilerplate)',
    '- `Test Steps`: numbered — `"1. Concrete action -> Observable result | 2. …"`',
    '- `Expected Result`: one clear observable sentence',
    '- `Test Data`: pipe-separated concrete values',
    '- `Notes`: related JIRA keys, performance targets, tool requirements',
  ].join('\n');

  fs.mkdirSync(instructionDir, { recursive: true });
  fs.writeFileSync(instructionPath, content, 'utf-8');
  return instructionPath;
}

// ─── CSV parser ───────────────────────────────────────────────────────────────
//
// Parses the CSV Bob produces back into TestCase[] for XLSX export and Jira
// attachment. Uses a simple state machine to handle quoted, multi-line fields.

export function parseCsvToTestCases(csvPath: string, issueKey: string): TestCase[] {
  if (!fs.existsSync(csvPath)) return [];
  const raw = fs.readFileSync(csvPath, 'utf-8');
  const rows = parseCSVRows(raw);
  if (rows.length < 2) return [];

  // Header: Test Case ID, Title, Priority, Type, Preconditions, Test Steps, Expected Result, Test Data, Notes
  const testCases: TestCase[] = [];
  for (let i = 1; i < rows.length; i++) {
    const row = rows[i];
    if (row.length < 7) continue;
    const [id, title, priority, type, precondsRaw, stepsRaw, expectedResult, testDataRaw, notes] = row;
    if (!id || !title) continue;

    const preconditions = precondsRaw
      ? precondsRaw.split('|').map(s => s.trim()).filter(Boolean)
      : [];

    const testSteps: TestStep[] = [];
    if (stepsRaw) {
      // Parse "1. Action -> Expected | 2. Action -> Expected"
      const stepParts = stepsRaw.split(/\s*\|\s*(?=\d+\.)|\n(?=\d+\.)/);
      for (const part of stepParts) {
        const m = part.match(/^(\d+)\.\s+(.+?)\s*->\s*(.+)$/s);
        if (m) {
          testSteps.push({
            stepNumber: parseInt(m[1], 10),
            action: m[2].trim(),
            expectedResult: m[3].trim(),
          });
        }
      }
    }

    const testData = testDataRaw
      ? testDataRaw.split('|').map(s => s.trim()).filter(Boolean)
      : [];

    testCases.push({
      id: id.trim(),
      title: title.trim(),
      priority: (priority?.trim() || 'Medium') as TestPriority,
      type: (type?.trim() || 'Functional') as TestType,
      category: type?.trim() || 'Functional',
      preconditions,
      testSteps,
      expectedResult: expectedResult?.trim() || '',
      testData,
      notes: notes?.trim() || `Source: ${issueKey}`,
      automatable: !['Performance', 'Accessibility', 'Documentation'].includes(type?.trim()),
    });
  }
  return testCases;
}

// Simple CSV tokeniser that handles double-quoted fields with embedded commas/newlines
function parseCSVRows(csv: string): string[][] {
  const rows: string[][] = [];
  let row: string[] = [];
  let field = '';
  let inQuotes = false;
  let i = 0;
  const text = csv.replace(/\r\n/g, '\n').replace(/\r/g, '\n');

  while (i < text.length) {
    const ch = text[i];
    if (inQuotes) {
      if (ch === '"') {
        if (text[i + 1] === '"') { field += '"'; i += 2; continue; }
        inQuotes = false; i++; continue;
      }
      field += ch; i++; continue;
    }
    if (ch === '"') { inQuotes = true; i++; continue; }
    if (ch === ',') { row.push(field); field = ''; i++; continue; }
    if (ch === '\n') {
      row.push(field); field = '';
      if (row.some(c => c.trim())) rows.push(row);
      row = []; i++; continue;
    }
    field += ch; i++;
  }
  if (field || row.length) { row.push(field); if (row.some(c => c.trim())) rows.push(row); }
  return rows;
}

// ─── generateTestCases() — deterministic fallback ─────────────────────────────
//
// Used when Bob is NOT available (standalone CLI, dry-run without Bob context).
// Produces minimal but well-structured test cases from the issue analysis.
// NOT used when running through the Bob-driven workflow.

export function generateTestCases(issue: JiraIssue, analysis: IssueAnalysis, _detailed: boolean): TestCase[] {
  const testCases: TestCase[] = [];
  let counter = 0;

  for (const group of analysis.scenarioGroups) {
    for (const scenario of group.scenarios) {
      counter++;
      const type = inferType(group.category, scenario);
      const priority = inferPriority(scenario, type, issue.priority);
      const subject = scenario.replace(/^(verify|validate|ensure|check|confirm)\s+/i, '').trim();

      testCases.push({
        id: `${issue.key}-TC-${pad(counter)}`,
        title: scenario.charAt(0).toUpperCase() + scenario.slice(1),
        priority,
        type,
        category: group.category,
        preconditions: buildMinimalPreconditions(issue, scenario),
        testSteps: buildMinimalSteps(subject, type, issue),
        expectedResult: type === 'Negative'
          ? 'System rejects the invalid input or access attempt with a descriptive error message'
          : `${subject.charAt(0).toUpperCase() + subject.slice(1)} works correctly and all acceptance criteria are satisfied`,
        testData: buildMinimalTestData(type, issue),
        notes: issue.linkedIssues.length ? `Related: ${issue.linkedIssues.slice(0, 3).map(l => l.key).join(', ')}` : `Source: ${issue.key}`,
        automatable: !['Performance', 'Accessibility', 'Documentation'].includes(type),
      });
    }
  }

  return testCases;
}

// ─── Minimal helpers for the fallback generator ───────────────────────────────

function inferType(category: string, scenario: string): TestType {
  const l = scenario.toLowerCase();
  if (category === 'Security')                                                    return 'Security';
  if (category === 'Performance')                                                 return 'Performance';
  if (category === 'Accessibility')                                               return 'Accessibility';
  if (category === 'Documentation')                                               return 'Documentation';
  if (category === 'Regression')                                                  return 'Regression';
  if (category === 'Migration' || category === 'API / Integration')              return 'Integration';
  if (category === 'Negative / Error Handling')                                  return 'Negative';
  if (l.match(/invalid|error|fail|exception|reject|unauthori|missing|empty|boundary|timeout|500|401|403/)) return 'Negative';
  return 'Functional';
}

function inferPriority(scenario: string, type: TestType, issuePriority: string): TestPriority {
  const l = scenario.toLowerCase();
  if (issuePriority.toLowerCase().match(/critical|blocker/)) return 'Critical';
  if (l.match(/happy path|valid input|core|migration.*happy/)) return 'High';
  if (l.match(/data loss|corrupt|clean.?up|401|403/)) return 'High';
  if (issuePriority.toLowerCase().match(/high|major/) && ['Functional', 'Integration', 'Negative'].includes(type)) return 'High';
  if (l.match(/edge|boundary|concurrent|partial|incognito|cross.browser|feature flag/)) return 'Medium';
  if (['Performance', 'Accessibility'].includes(type)) return 'Medium';
  if (type === 'Documentation') return 'Low';
  return 'Medium';
}

function buildMinimalPreconditions(issue: JiraIssue, scenario: string): string[] {
  const sl = scenario.toLowerCase();
  const pre: string[] = [];

  // ── Role precondition — always scenario-specific, never generic ────────────
  if (sl.match(/unauthenticated|no token|not logged/))  pre.push('User is NOT logged in / session is expired');
  else if (sl.match(/b2b.?admin/))                       pre.push('User is logged in with B2B Admin role');
  else if (sl.match(/b2b.?viewer/))                      pre.push('User is logged in with B2B Viewer role');
  else if (sl.match(/b2b.?workspace.?user/))             pre.push('User is logged in with B2B Workspace User role');
  else if (sl.match(/b2b.?user/))                        pre.push('User is logged in with B2B User role');
  else if (sl.match(/ipaas.?admin/))                     pre.push('User is logged in with iPaaS Admin role');
  else if (sl.match(/service.?owner/))                   pre.push('User is logged in with Service Owner role');
  else if (sl.match(/service.?admin/))                   pre.push('User is logged in with Service Admin role');
  else if (sl.match(/service.?viewer/))                  pre.push('User is logged in with Service Viewer role');
  else                                                   pre.push('User is logged in with a valid authenticated session');

  // ── Feature-specific preconditions — only add when the scenario directly
  //    tests that state, not as boilerplate on every row ─────────────────────
  if (sl.match(/b2b.+disabled|disable.+b2b|capability.+off/))
    pre.push('B2B Integration capability is DISABLED');
  else if (sl.match(/b2b.+enabled|enable.+b2b|capability.+on/) && sl.match(/toggle|flag|switch/))
    pre.push('B2B Integration capability is ENABLED');

  // Only for scenarios that explicitly test incognito/private mode
  if (sl.match(/incognito|private.?browsing|private.?window/))
    pre.push('Browser is in incognito / private-browsing mode');

  // Only for scenarios that explicitly test a named API call
  if (sl.match(/timeout|api.+fail|mock.+500|downstream.+error/))
    pre.push('Downstream service is mocked to return HTTP 500 or timeout');

  // Add component only when scenario names a specific component (not generic "SCI-IWHI deployed")
  if (issue.components.length && sl.match(new RegExp(issue.components.map(c => c.toLowerCase().replace(/[^a-z0-9]/g, '.*')).join('|'))))
    pre.push(`${issue.components.find(c => sl.includes(c.toLowerCase()))} component is deployed`);

  return pre;
}

function buildMinimalSteps(subject: string, type: TestType, issue: JiraIssue): TestStep[] {
  switch (type) {
    case 'Negative': return [
      { stepNumber: 1, action: `Navigate to the feature entry point for: ${subject.slice(0, 60)}`, expectedResult: 'Page / section loads successfully' },
      { stepNumber: 2, action: `Attempt the operation with invalid, missing, or boundary data`, expectedResult: 'System rejects the input or denies the action' },
      { stepNumber: 3, action: 'Observe the error feedback returned to the user', expectedResult: 'A descriptive, user-friendly error message is displayed' },
      { stepNumber: 4, action: 'Verify the system state has not been corrupted', expectedResult: 'Data integrity is maintained; no partial writes occurred' },
      { stepNumber: 5, action: 'Retry with valid data', expectedResult: 'System accepts the valid input and proceeds normally' },
    ];
    case 'Security': return [
      { stepNumber: 1, action: `Attempt: ${subject.slice(0, 60)} as an unauthenticated user`, expectedResult: 'Request is rejected — HTTP 401 Unauthorised' },
      { stepNumber: 2, action: 'Repeat with valid session but insufficient permissions', expectedResult: 'Request is rejected — HTTP 403 Forbidden' },
      { stepNumber: 3, action: 'Attempt with an expired token', expectedResult: 'Session invalidated; user prompted to re-authenticate' },
      { stepNumber: 4, action: 'Verify all API calls use HTTPS', expectedResult: 'All traffic is encrypted; no plain HTTP calls' },
      { stepNumber: 5, action: "Verify User A cannot access User B's data", expectedResult: 'Data isolation is enforced; cross-user access is denied' },
    ];
    case 'Performance': return [
      { stepNumber: 1, action: `Run baseline performance test for: ${subject.slice(0, 60)}`, expectedResult: 'Response time < 2s under single-user load' },
      { stepNumber: 2, action: 'Simulate 50 concurrent users performing the same action', expectedResult: 'P95 response time < 5s; error rate < 1%' },
      { stepNumber: 3, action: 'Monitor CPU, memory, and DB query metrics during load', expectedResult: 'No resource exhaustion; metrics within acceptable thresholds' },
      { stepNumber: 4, action: 'Repeat test 3 times and compare results', expectedResult: 'Results are stable; no significant variance' },
    ];
    case 'Integration': return [
      { stepNumber: 1, action: 'Confirm all dependent services / APIs are running and health checks pass', expectedResult: 'All downstream services respond with HTTP 200' },
      { stepNumber: 2, action: `Trigger the integration flow: ${subject.slice(0, 80)}`, expectedResult: 'Request dispatched; HTTP 200 / 201 acknowledged' },
      { stepNumber: 3, action: 'Verify request payload matches the API contract', expectedResult: 'Payload contains all required fields in the correct format' },
      { stepNumber: 4, action: 'Verify data is correctly propagated to the target system', expectedResult: 'Source and target records are consistent' },
      { stepNumber: 5, action: 'Simulate an integration failure (mock HTTP 500 from downstream)', expectedResult: 'System handles the failure gracefully with retry or fallback logic' },
    ];
    case 'Regression': return [
      { stepNumber: 1, action: 'Execute the baseline smoke test suite for all areas affected by this change', expectedResult: 'All existing smoke tests pass without modification' },
      { stepNumber: 2, action: `Test the previously working behaviour: ${subject.slice(0, 80)}`, expectedResult: `Existing functionality is unaffected by ${issue.key} changes` },
      { stepNumber: 3, action: 'Compare test results against the last known-good build', expectedResult: 'Result delta is zero; no new failures introduced' },
    ];
    case 'Accessibility': return [
      { stepNumber: 1, action: 'Open the feature in Chrome with keyboard-only navigation', expectedResult: 'All interactive elements are reachable via Tab key in logical order' },
      { stepNumber: 2, action: `Navigate and interact with: ${subject.slice(0, 60)} using keyboard only`, expectedResult: 'Action can be completed without a mouse; focus indicators are visible' },
      { stepNumber: 3, action: 'Enable NVDA (Windows) or VoiceOver (macOS) and navigate the feature', expectedResult: 'Screen reader correctly announces all labels, states, and role changes' },
      { stepNumber: 4, action: 'Verify colour contrast ratio using browser DevTools', expectedResult: 'Contrast ratio ≥ 4.5:1 for normal text (WCAG 2.1 AA)' },
    ];
    case 'Documentation': return [
      { stepNumber: 1, action: `Search codebase for TODO / FIXME comments related to ${issue.key}`, expectedResult: 'No unresolved TODO/FIXME comments remain' },
      { stepNumber: 2, action: `Search for deprecated references: ${subject.slice(0, 60)}`, expectedResult: 'No deprecated APIs or patterns remain in affected files' },
      { stepNumber: 3, action: 'Review README / inline documentation for the affected component', expectedResult: 'Documentation reflects the current implementation and is up to date' },
    ];
    default: {
      // Derive the most specific navigation hint possible from the issue context
      const nav = issue.summary
        ? `Navigate to the area described by "${issue.summary.slice(0, 60)}"`
        : `Navigate to the relevant page for: ${subject.slice(0, 60)}`;

      // Derive a concrete action from the scenario subject
      const action = subject.length > 0
        ? `Perform the action described as: "${subject.slice(0, 80)}"`
        : `Perform the primary action as documented in ${issue.key}`;

      // Derive a concrete assertion from the AC, not a generic phrase
      const acHint = issue.acceptanceCriteria
        ? issue.acceptanceCriteria.split('\n').find(l => l.trim().length > 20)?.trim().slice(0, 120) ?? ''
        : '';
      const assertion = acHint
        ? `Verify: ${acHint}`
        : `Verify the result matches the specific outcome stated in ${issue.key} acceptance criteria`;

      return [
        { stepNumber: 1, action: nav, expectedResult: 'Page loads without errors; HTTP 200; no stuck spinner' },
        { stepNumber: 2, action: action, expectedResult: 'System accepts the action; expected state change or response occurs' },
        { stepNumber: 3, action: assertion, expectedResult: 'Observable outcome satisfies the named acceptance criteria item' },
        { stepNumber: 4, action: 'Verify no unintended side-effects on adjacent UI sections, roles, or data records not targeted by this scenario', expectedResult: 'Adjacent features are unaffected; no regressions introduced' },
        { stepNumber: 5, action: 'Open browser DevTools → Console tab; check for JS errors, uncaught exceptions, unexpected 4xx/5xx responses', expectedResult: 'Console is clean; all network calls return expected HTTP status codes' },
      ];
    }
  }
}

function buildMinimalTestData(type: TestType, issue: JiraIssue): string[] {
  switch (type) {
    case 'Negative':      return ['Empty string / null value', 'Special characters: <script>alert(1)</script>', 'String exceeding max length (>255 chars)', 'Boundary value: min−1 and max+1'];
    case 'Security':      return ['Unauthenticated request (no token)', 'Expired JWT token', "Token belonging to a different user", 'Role without required permission'];
    case 'Performance':   return ['1 concurrent user (baseline)', '50 concurrent users (load test)', 'Response time target: < 500ms (API), < 2s (page load)'];
    case 'Integration':   return ['Valid request payload per API contract', 'Mock HTTP 500 from downstream service', 'Mock network timeout (30s)', 'Empty response body from API'];
    case 'Accessibility': return ['Keyboard-only navigation (no mouse)', 'NVDA on Windows / VoiceOver on macOS', 'axe DevTools scan', 'Colour Contrast Analyser — target 4.5:1'];
    default:              return [`Valid data as defined in ${issue.key} acceptance criteria`];
  }
}

// ─── TestCaseAgentGenerator class ─────────────────────────────────────────────
//  Thin wrapper used by the CLI (scripts/jira-test-case-generator.ts).
//  When running under Bob's workflow, use generateWithBob() directly.

export class TestCaseAgentGenerator {
  constructor(
    private readonly issueKey: string,
    private readonly format: OutputFormat = 'csv',
    private readonly outputPath: string | undefined = undefined,
    private readonly detailed: boolean = false,
  ) {}

  async generate(): Promise<void> {
    console.log(`\n🔍  Fetching ${this.issueKey}…`);
    const issue = await fetchFromRestApi(this.issueKey);
    console.log(`  📋  ${issue.key}: ${issue.summary}`);

    // Build full context (includes prompts/test-case-generation.md)
    const ctx = buildContext(issue);
    const analysis = analyseIssue(issue);

    const outDir = path.join(process.cwd(), 'test-cases');
    fs.mkdirSync(outDir, { recursive: true });

    const base = this.outputPath
      ? path.resolve(this.outputPath).replace(/\.[^.]+$/, '')
      : path.join(outDir, `${this.issueKey}-test-cases`);

    // Write the Bob instruction file — Bob reads this and writes the CSV
    const instructionPath = writeBobInstructionFile(ctx, `${base}.csv`, outDir);
    console.log(`\n  📝  Bob instruction file → ${instructionPath}`);
    console.log(`  ℹ️   Bob: read the instruction file above and generate the CSV.`);
    console.log(`  ℹ️   After Bob writes the CSV, run with --from-csv to convert to XLSX/MD.\n`);

    // If a CSV already exists (Bob already generated it), convert to other formats
    const csvPath = `${base}.csv`;
    if (fs.existsSync(csvPath)) {
      const testCases = parseCsvToTestCases(csvPath, this.issueKey);
      console.log(`  ✅  ${testCases.length} test cases loaded from existing CSV`);

      if (this.format === 'xlsx') {
        fs.writeFileSync(`${base}.xlsx`, formatAsXLSX(testCases, issue, analysis));
        console.log(`  💾  XLSX → ${base}.xlsx`);
      }
      if (this.format === 'markdown') {
        fs.writeFileSync(`${base}.md`, formatAsMarkdown(testCases, issue, analysis), 'utf-8');
        console.log(`  💾  MD   → ${base}.md`);
      }
      if (this.format === 'json') {
        fs.writeFileSync(`${base}.json`, JSON.stringify({ issue: { key: issue.key, summary: issue.summary }, generatedAt: new Date().toISOString(), testCases }, null, 2), 'utf-8');
        console.log(`  💾  JSON → ${base}.json`);
      }
    }
  }
}

// Made with Bob
